version: "3.9"

services:
  dispatcher:
    image: fteychene/cloud-cadavre-exquis-dispatcher-bis:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      SUBJECT_URL: "http://providers-subject:8080"
      VERB_URL: "http://providers-subject:8080"
      ADJECTIVE_URL: "http://providers-adj:8080"
    networks:
      - cadaver
      - provider
  lb:
    image: nginx:1.19
    volumes:
      - type: bind
        source: $PWD/docker/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - cadaver
      - provider
  providers-subject:
    image: fteychene/cloud-cadavre-exquis-provider-bis:1.0-SNAPSHOT
    depends_on:
      - registers
    environment:
      REGISTER_URLS: "http://registers:8080"
      WORD_TYPE: SUBJECT
    networks:
      - provider
  providers-verb:
    image: fteychene/cloud-cadavre-exquis-provider-bis:1.0-SNAPSHOT
    depends_on:
      - registers
    environment:
      REGISTER_URLS: "http://registers:8080"
      WORD_TYPE: VERB
    networks:
      - provider
  providers-adj:
    image: fteychene/cloud-cadavre-exquis-provider-bis:1.0-SNAPSHOT
    depends_on:
      - registers
    environment:
      REGISTER_URLS: "http://registers:8080"
      WORD_TYPE: ADJECTIVE
    networks:
      - provider
networks:
  cadaver:
  provider: